In [40]:
from transformers import AutoTokenizer, TFAutoModel
import tensorflow as tf

In [41]:
import numpy as np

In [42]:
import tensorflow.keras as keras

In [43]:
import pandas as pd

In [44]:
df=pd.read_csv('train.csv')
df.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['target'], test_size=0.2, random_state=42)

In [46]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [50]:
X_train.head()

4996    Courageous and honest analysis of need to use ...
3263    @ZachZaidman @670TheScore wld b a shame if tha...
4907    Tell @BarackObama to rescind medals of 'honor'...
2855    Worried about how the CA drought might affect ...
4716    @YoungHeroesID Lava Blast &amp; Power Red #Pan...
Name: text, dtype: object

In [55]:
X =df['text']
y=df['target']
X

0       Our Deeds are the Reason of this #earthquake M...
1                  Forest fire near La Ronge Sask. Canada
2       All residents asked to 'shelter in place' are ...
3       13,000 people receive #wildfires evacuation or...
4       Just got sent this photo from Ruby #Alaska as ...
                              ...
7608    Two giant cranes holding a bridge collapse int...
7609    @aria_ahrary @TheTawniest The out of control w...
7610    M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...
7611    Police investigating after an e-bike collided ...
7612    The Latest: More Homes Razed by Northern Calif...
Name: text, Length: 7613, dtype: object

In [56]:
embeddings = model.encode(X.tolist())

In [60]:
# Define a simple neural network
nn_model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(384,)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')  # For binary classification
])

# Compile the model
nn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
nn_model.fit(embeddings, y, epochs=50, batch_size=32)

Epoch 1/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 1s 885us/step - accuracy: 0.7534 - loss: 0.5584
Epoch 2/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8181 - loss: 0.4171
Epoch 3/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.8176 - loss: 0.4082
Epoch 4/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.8285 - loss: 0.3880
Epoch 5/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8342 - loss: 0.3819
Epoch 6/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.8313 - loss: 0.3768
Epoch 7/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8424 - loss: 0.3550
Epoch 8/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.8548 - loss: 0.3347
Epoch 9/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8579 - loss: 0.3227
Epoch 10/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.8669 - loss: 0.3165
Epoch 11/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8635 - loss: 0.3115
Epoch 12/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.8812 - loss: 0.2889
Epoch 13/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.8878 - loss: 0.2764
Epoch 14/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.8853 - loss: 0.2788
Epoch 15/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.8969 - loss: 0.2592
Epoch 16/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.9004 - loss: 0.2457
Epoch 17/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.9135 - loss: 0.2279
Epoch 18/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.9156 - loss: 0.2215
Epoch 19/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.9214 - loss: 0.2145
Epoch 20/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.9216 - loss: 0.2062
Epoch 21/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.9307 - loss: 0.1897
Epoch 22/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.9414 - loss: 0.1781
Epoch 23/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.9483 - loss: 0.1673
Epoch 24/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.9486 - loss: 0.1673
Epoch 25/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.9474 - loss: 0.1567
Epoch 26/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.9567 - loss: 0.1352
Epoch 27/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.9685 - loss: 0.1253
Epoch 28/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.9711 - loss: 0.1227
Epoch 29/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.9711 - loss: 0.1164
Epoch 30/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.9724 - loss: 0.1087
Epoch 31/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.9737 - loss: 0.1048
Epoch 32/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.9731 - loss: 0.0982
Epoch 33/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.9765 - loss: 0.0965
Epoch 34/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step - accuracy: 0.9771 - loss: 0.0887
Epoch 35/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.9830 - loss: 0.0781
Epoch 36/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.9808 - loss: 0.0789
Epoch 37/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.9838 - loss: 0.0742
Epoch 38/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.9835 - loss: 0.0711
Epoch 39/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.9809 - loss: 0.0726
Epoch 40/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.9830 - loss: 0.0653
Epoch 41/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.9801 - loss: 0.0669
Epoch 42/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.9846 - loss: 0.0618
Epoch 43/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.9837 - loss: 0.0615
Epoch 44/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.9827 - loss: 0.0605
Epoch 45/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.9833 - loss: 0.0559
Epoch 46/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.9853 - loss: 0.0534
Epoch 47/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.9849 - loss: 0.0517
Epoch 48/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.9853 - loss: 0.0488
Epoch 49/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9871 - loss: 0.0477
Epoch 50/50
238/238 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.9801 - loss: 0.0561

In [82]:
df_new=pd.read_csv('test.csv')
df_new.shape

(3263, 4)

In [85]:
X_test_new=df_new['text']
X_test_new.shape

(3263,)

In [86]:
test_embeddings=model.encode(X_test_new.to_list())

In [87]:
test_embeddings.shape

(3263, 384)

In [88]:
predictions = nn_model.predict(test_embeddings)

102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step

In [89]:
predictions.shape

(3263, 1)

In [90]:
id=[i for i in df_new['id']]
pred=[]
for i in predictions:
    if i<0.5:
        pred.append(0)
    else:
        pred.append(1)

In [95]:
# Create a DataFrame to hold the results
output_df = pd.DataFrame({'id':id,'target':pred})

output_df

         id  target
0         0       0
1         2       1
2         3       0
3         9       1
4        11       1
...     ...     ...
3258  10861       1
3259  10865       1
3260  10868       1
3261  10874       1
3262  10875       1

[3263 rows x 2 columns]

In [96]:
# Save to CSV
output_df.to_csv('model_predictions.csv', index=False)

print("Predictions saved to 'model_predictions.csv'")

Predictions saved to 'model_predictions.csv'